### PR TITLE
PR label removal in my example

### PR DESCRIPTION
**Pull request by maelle**
I've just made this edit in https://github.com/r-hub/docs/, see [test PR](https://github.com/r-hub/docs/pull/24) and the workflow now feels smoother.

### CODE REVIEW

**Review by SuperKogito — APPROVED** [review]

**Comment by SuperKogito** [comment]
Looks great @maelle, nice work :clap:

**Comment by vsoch** [comment]
Woot! @SuperKogito next time please squash and merge.

**Comment by maelle** [comment]
Can't squash and merge be made a default somehow, btw?

**Comment by vsoch** [comment]
Yes, good idea! If it’s a single commit with a clean message or rebased it’s not needed, however. @SuperKogito what do you think - should it be made default as a reminder (for cases unlike those I mentioned?)

**Comment by maelle** [comment]
Just for info, although you probably know where to find the info https://help.github.com/en/github/administering-a-repository/configuring-commit-squashing-for-pull-requests

**Comment by SuperKogito** [comment]
I think I agree @vsoch I mean squashing would result in clean concise commits, which is nice to have. On the other hand if the commits affect some code, it would be better to see all the commits imo since it would help understand the developer logic in case any debugging is needed. So maybe we just keep that in mind or we default squash merging here but rebase merge in the urlchecker-python, what do you think?

**Pull request merged**
