### PR TITLE
Examples table

### LINKED ISSUE #62: Make it easier to look through real-life examples?
Could the list of examples at the end of the README be a table with

* community name, linking to repo as it is now the case
* workflow file presented as `[workflow running blablabla every blablabla](permalink to workflow file)`
* example log?

I'm asking because that's what I go look for in example repos.

### PR DESCRIPTION
**Pull request by maelle**
Fix #62

### CODE REVIEW

**Comment by maelle** [comment]
Given the examples don't all use the latest version of the action, I was wondering whether this makes sense (as opposed to making the table for a test repo whose workflows would be kept up-to-date). :thinking: At the same time it's nice to see others have adopted it as a complement to [GitHub search](https://github.com/search?l=YAML&q=urlstechie%2Furlchecker-action&type=Code).

**Comment by SuperKogito** [comment]
You make a great point but sadly I don't have a clear answer to this. My idea/ vision for the test-repo is to have a packed workflow exploring/testing almost all variant/inputs of the action. The workflow will be triggered by any new release of the action, that way we will be the first to test the action. I am still not sure about how all this will look like once implemented and whether it will cause a conflict against your suggestion, that's why I cannot tell for sure. @vsoch will surely provide a nice input on this.

**Comment by vsoch** [comment]
I didn't even see this! The table is missing some spacers, I checked it's rendering and it's off a bit :)

image

**Comment by vsoch** [comment]
Oops nevermind, bad copy paste! Here is how it looks

image

**Review by vsoch — CHANGES_REQUESTED** [review]
This looks great! it's a much nicer looking table than the one that I threw together.

One small change - let's change the long name for the "United States Research Software..." to just be "us-rse." It is throwing off the balance of the table and will look cleaner / better as the shorter name.

**Comment by maelle** [comment]
Done! :heavy_check_mark:

**Comment by SuperKogito** [comment]
I prefer the long name, not everyone know about the abbreviations plus that's the name on the organization page, so i don't see why do we favor the abbreviations? same for r-hub.

**Review by vsoch — APPROVED** [review]
Perfecto! Let's get this merged.

**Comment by vsoch** [comment]
Here is the final table! The spacing is just right now, aesthetically pleasing. 
image

The one future tweak we can do is to give that table it's own proper section - in my PR #64 I was calling it "In the Wild" or something like that.

**Comment by maelle** [comment]
And there could also be a sentence linking to a GitHub search of YAML files mentioning the action. 🤔

**Comment by maelle** [comment]
Was @superkogito answer above missed?

**Comment by maelle** [comment]
(R-hub is not an abbreviation though)

**Comment by vsoch** [comment]
I'm a part of us-rse, so I think I can solidly say that it's referred to very commonly as us-rse, especially around documentation for the organization and on GitHub. So that along with how much nicer the table renders is a good call I think. I wrote that original link also, and while it might be appropriate for a single list of names, it makes the table look weird to have it so long!

@maelle that would be a good idea too!

**Comment by vsoch** [comment]
I also don't think people looking for examples care so much about a specific org (they'd rather see an example) and if they do, they can click the link and read the full (extremely long!) name, lol.

**Comment by SuperKogito** [comment]
I still disagree xD but two votes beat one, so we can to other things ;)

**Pull request merged**
