### PR TITLE
Ensure that INPUT_FILE_TYPES is quoted

### PR DESCRIPTION
**Pull request by vsoch**
This is a test to address part of the issue in #76.

### CODE REVIEW

**Review by SuperKogito — APPROVED** [review]
Lgtm ;)

**Comment by vsoch** [comment]
@SuperKogito take a look at our discussion in #76 - it's not clear that this strategy will work (and if it does not we need to rethink how to specify this variable.) It seems to work on the command line, but (so far) not the action

**Comment by SuperKogito** [comment]
As I mentioned in #76 this doesn't seem to be the problem I think, so we might want to drop this.

**Comment by vsoch** [comment]
Ok, so don't merge, just close? Sorry I missed your other comment - long day!

**Comment by SuperKogito** [comment]
no worries, I will handle this. Well the edits in here are not going to solve the #76 . For now I gave the user a working alternative. 
Fixing this will require edits to the python library, which I will try to do after the acceleration edits this weekend. I am closing this for now :)

**Pull request closed without merging**
