### PR TITLE
Create urlchecker-pr-label.yml

### LINKED ISSUE #44: Can the URL checks run on the files added/edited by a PR only?
Sorry for asking without trying first!

I found this repo via https://vsoch.github.io/2020/urlchecker/, it looks really cool 👏

### PR DESCRIPTION
**Pull request by maelle**
Fix #44 

@vsoch I'm guessing a lot more docs are needed? I'd make this more exhaustive tomorrow.

My [other workflow](https://github.com/r-hub/docs/blob/master/.github/workflows/urlchecks.yml) is just a CRON job, so probably not very interesting.

### CODE REVIEW

**Comment by vsoch** [comment]
Sounds good!

**Comment by SuperKogito** [comment]
This looks good to me :+1:  but I would let @vsoch take a look first ;)

**Comment by vsoch** [comment]
Taking a look!

**Review by vsoch — APPROVED** [review]
Beautiful! This is such an awesome use case, thanks @maelle !

**Comment by maelle** [comment]
Thanks for helping me create it! I like it because I felt one check by commit was potentially too much, so now I'll check URLs with intent (and if I forget I still have the monthly run over the whole repo anyway).

**Pull request merged**
