### PR TITLE
adding retry parameter to URLchecker, will double time between retrie…

### PR DESCRIPTION
**Pull request by vsoch**
This pull request will attempt to address #15 by adding a retry parameter to the action. Specifically:

 - the retry_count determines the number of retries to do. Each retry starts at 2 seconds, and then is doubled as we advance (2, 4, 8, 16, etc.)
 - I think #16 is a bug so I moved it out in the loop, let me know if this is intentional or I'm missing something!
 - I exposed the timeout to requests to the user, with the default being what it already was set to (5 seconds)
 - I changed the booleans in the action.yml to be all lowercase, mostly for aesthetics because it renders a different color in the editor and it's easier to see the booleans. To allow for either lower or uppcase set by a user, the envar for each is parsed and then made lowercase with .lower().
 
Currently, we print and add to the list of check_results each retry attempt, the idea being that a retry could have different results. I'm thinking we might want to refactor this so that the failed url is only added _after_ it's failed all retries - that way we don't have the same url in a failed / success list if it worked on retry.

I held off on further implementation because I think @SuperKogito you had a specific idea for error checking that I wanted to ask for more detail about. Take a look here, and let me know what we should do next!

Signed-off-by: vsoch <vsochat@stanford.edu>

### CODE REVIEW

**Comment by vsoch** [comment]
okay I updated the PR so that the act of checking (and determining if we need retry) is separate from adding a final result to a list. I'm not sure what the best way to test this is, I'll wait to discuss with you further.

**Review by SuperKogito — APPROVED** [review]
This PR looks very good! Great job @vsoch :clap:

**Review by SuperKogito — APPROVED** [review]

**Comment by vsoch** [comment]
Awesome! How would you like to test?

**Comment by SuperKogito** [comment]
> the retry_count determines the number of retries to do. Each retry starts at 2 seconds, and then is doubled as we advance (2, 4, 8, 16, etc.)

This was a great idea! :clap: 

The testing can be done using the other [repo](https://github.com/urlstechie/URLs-checker-test-repo) in this organization, I usually just release the updates, edit the action.yml and trigger a build and just observe the results. I also rely on bugs reports from other users like @shahzebsiddiqui. I am open to better alternatives if you have any suggestions. 

Concerning the error checking idea, I will be opening a new issue (among others) with a clearer description and we can discuss it there, to see how practical is it and how useful could it be.  

Also if you have any ideas of improvements, feel free to open a PR or an issue to discuss it. Right now, my goal is to have a stable version (no bugs or almost none), with the option to commit a report file to the repo (upcoming feature, this is actually the point of putting the errors in a list) and eventually maybe build a bot for the action. In parallel, it would be also important to get more attention from users in order for the project to progress further. 

Again thank you for your PR! the newly implemented features will heavily help get more attention :smile:

**Comment by vsoch** [comment]
Great! Yes and we can test it using buildtest and then the usrse repo, likely later today (it’s still wee hours of the morning here) so stay tuned! I’ll also check the other repo in the org later to see if it ran ok, and I can follow up with another PR if any tweaks are needed.

**Comment by SuperKogito** [comment]
Sounds perfect to me, have a nice productive day ;)

**Pull request merged**
