### PR TITLE
preparing PR for new release (0.0.22) of urlchecker python.

### PR DESCRIPTION
**Pull request by vsoch**
This PR test will not work until the container has been built after https://github.com/urlstechie/urlchecker-python/pull/51 is deployed.

Signed-off-by: vsoch <vsoch@users.noreply.github.com>

### CODE REVIEW

**Comment by vsoch** [comment]
@SuperKogito and @rootwork this should work for the just released version 0.0.22.

**Review by SuperKogito — APPROVED** [review]
@vsoch  This looks good to me :) 
but there is a warning related to `--force-pass`  in the CI-tests. I think we need to add  a`force_pass` section in [action.yml](https://github.com/urlstechie/urlchecker-action/blob/master/action.yml)

**Comment by vsoch** [comment]
okay force pass is added.

**Review by SuperKogito — APPROVED** [review]

**Comment by vsoch** [comment]
okay, let's merge! The true test will be when someone tries it out, and if there are some tiny issues that's okay, we'll fix them asap. It's definitely hard to test gh-actions fully so we can only do our best.

**Pull request merged**
