### PR TITLE
updating action to include --files argument

### PR DESCRIPTION
**Pull request by vsoch**
This pull request will add the `--files` flag, an argument exposed as `include_files` to allow the user to specify one or more file paths or patterns to include.

Signed-off-by: vsoch <vsochat@stanford.edu>

### CODE REVIEW

**Comment by vsoch** [comment]
Bug will be fixed by https://github.com/urlstechie/urlchecker-python/pull/30

**Comment by vsoch** [comment]
@SuperKogito I think there are issues with your test repo now... taking a look.

**Review by SuperKogito — APPROVED** [review]

**Comment by SuperKogito** [comment]
yeah, I think our testing setup is not that efficient atm, I am working on an update that hopefully will make our lives easier in the future ;)

**Comment by vsoch** [comment]
Great! I added a quick folder to the test repo, "test_action" that is (for now) a very bad / basic use case. I'd like to suggest that we do further work to improve this folder (along with test cases here) and then the urlchecker-python tests can also be limited to some subset, if necessary.

And wow @SuperKogito I would do just about anything to remove this codacy check - having preference for whether the list item has a space in front of it or not a good use of my time and it's really starting to bother me.

**Comment by vsoch** [comment]
@SuperKogito please disable Codeacy for this repository it's not necessary and is hurting development.

**Comment by SuperKogito** [comment]
This looks good for now :clap. 
Concerning the codacy we can drop it, if is that bad or just remove it in PRs. I only like to have it, just to have an overview on the code quality and get a different perspective on what to improve. However, I agree that some of its reports/ detected low quality line makes no sense. So I will remove it from PRs ;)

**Comment by vsoch** [comment]
If you want to keep it, maybe just enable it for the entrypoint.sh file or similar.

**Comment by SuperKogito** [comment]
fixed in https://github.com/urlstechie/urlchecker-action/issues/49.

**Pull request merged**
