### PR TITLE
preparing to test action with web drivers!

### LINKED ISSUE #93: URL checker fails on URLs that work
e.g. https://github.com/pybamm-team/PyBaMM/runs/7115511512?check_suite_focus=true#step:4:631

Are there different settings we can use to make it work?

### PR DESCRIPTION
**Pull request by vsoch**
This will close #93 

Signed-off-by: vsoch <vsoch@users.noreply.github.com>

### CODE REVIEW

**Review by SuperKogito — APPROVED** [review]

**Comment by vsoch** [comment]
woo it worked! Okay @tinosulzer @rootwork would you care to test your repos against this branch? It should be the same urlchecker-action, but `@test-release-31-drivers`. If this works then I'll release https://github.com/urlstechie/urlchecker-python/pull/77 (with a new container build to ghcr.io with version 0.0.31) and then update and merge/release the action here!

**Comment by rootwork** [comment]
It's definitely working better. [I get some failed URLs](https://github.com/rootwork/rootwork.org/runs/7490818021?check_suite_focus=true) but they're all because of timeouts, I think. I did notice this:

`Message: invalid session id`

on several of the checks. Not sure if that's significant.

On the [second run](https://github.com/rootwork/rootwork.org/runs/7490898801?check_suite_focus=true) I didn't see that error message, and there were fewer URLs failing, all still because of timeouts I think. (Edit: The last URL, the Internet Archive one, is legitimately broken because of a typo. All the other failed ones should work though.)

**Comment by vsoch** [comment]
Let me take a look!

**Comment by vsoch** [comment]
okay @rootwork give it another try (e.g., just click re-run) ! It looks like a tab crashed and then those errors started happening, so I am trying two things:

1. scoping the browser session to just the check_urls run - e.g., we create the driver at the start, and close it when we are done, and this would be done by each worker. The one issue I think we might run into (which I'll add a fix for after we address this main issue) is if concurrent workers try using the same port (and then fail).
2. It looks like you can get this tab crash if the driver runs out of memory for a page, so I tried adding a flag that tells it to write to the /tmp filesystem instead. It might be slightly slower but (I think) should be more reliable.

**Comment by rootwork** [comment]
Got the `invalid` message on [a separate run](https://github.com/rootwork/rootwork.org/runs/7490956645?check_suite_focus=true) and a somewhat different set of failing URLs. A bunch of them are Twitter, which I imagine I'll just have to update the timeout and/or retries to get. The other problematic URLs are some of the `drupal.org` and `groups.drupal.org` ones, and for whatever reason, that `progressiveexchange.org` URL that keeps showing up.

[Edit: Just saw your new message; testing again.]

**Comment by vsoch** [comment]
okay going to push a fix for the ports in a second... will test here first.

**Comment by vsoch** [comment]
oup I see your message! I'll wait for your test before pushing changes!

**Comment by rootwork** [comment]
[Almost all the failing URLs](https://github.com/rootwork/rootwork.org/runs/7491017544?check_suite_focus=true) are now just Twitter.

**Comment by vsoch** [comment]
I think we're getting closer! Let me manually test that smaller list that are still failing, will report back.

**Comment by vsoch** [comment]
okay new changes are in - https://github.com/urlstechie/urlchecker-python/pull/77/commits/a9bf1564962176725805a024573c1377a3edf664 let's do another re-run! (and thank you for doing this to help!)

**Comment by rootwork** [comment]
[It passed!](https://github.com/rootwork/rootwork.org/runs/7491272640?check_suite_focus=true) Woo!

Thank you for ALL your work on this. I really appreciate it!

**Comment by vsoch** [comment]
Woo! Most definitely! I'm so glad to find a solution for these tricky urls too!

I'm going to release urlchecker-python, and then I'll be back here to finish up. Thank you for all the testing @rootwork !

**Comment by valentinsulzer** [comment]
Worked for me too :) https://github.com/pybamm-team/PyBaMM/runs/7491354319?check_suite_focus=true 

Thanks!

**Comment by valentinsulzer** [comment]
When I tried to use the released version 0.0.31, it passed but didn't seem to check anything https://github.com/pybamm-team/PyBaMM/runs/7491390710?check_suite_focus=true

**Comment by vsoch** [comment]
@tinosulzer can you give me more detail? I see a list of a ton of URLs at that action linked.

**Comment by valentinsulzer** [comment]
Yes you're right, I don't know why I thought that. Thanks again!

**Comment by vsoch** [comment]
ok phew!

**Pull request merged**
