### PR TITLE
Preparing updates to container base with debian buster and certifi

### PR DESCRIPTION
**Pull request by vsoch**
To follow up with https://github.com/urlstechie/urlchecker-action/issues/79, this better shows the changes on the branch (one line now that we have a base image with certifi and debian buster).

### CODE REVIEW

**Review by ax3l — APPROVED** [review]
:rocket: :sparkles:

**Comment by ax3l** [comment]
Tested in https://github.com/ECP-WarpX/WarpX/pull/2188

Does *not* yet solve it :-o
```
HTTPSConnectionPool(host='www.olcf.ornl.gov', port=443): Max retries exceeded with url: /frontier/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))
https://www.olcf.ornl.gov/frontier/
```

**Comment by vsoch** [comment]
Hmm, so I think we'd need something more detailed for the library - basically to skip checking certs all together. I'm a bit on the fence about this - it would be easy enough to whitelist these urls (and not disable checking). I think the checking is generally a good things, and the labs should be bothered about their cert setups. What do you think?

**Comment by ax3l** [comment]
For our ECP project, NERSC and OCLF URLs are quite important (users have to click on them to learn how to use the code on a system), so I thought to go down the rabbit hole instead of excluding them :sweat_smile:

**Comment by vsoch** [comment]
Totally makes sense! But would you want to disable cert checking all together just to make this superficially work (or are you okay adding to whitelist?) I think I would want to know when something doesn't work and then explicitly add to the whitelist. Either way I'd ask them about the certs setup - it sort of smells like self signed certificates or something funny like that.

**Comment by ax3l** [comment]
Hm,
- https://www.ssllabs.com/ssltest/analyze.html?d=www.olcf.ornl.gov&latest
- https://www.ssllabs.com/ssltest/analyze.html?d=docs%2ddev.nersc.gov&latest

have indeed chain issues. Jeeze.

**Comment by ax3l** [comment]
I'll open tickets with both...

**Comment by vsoch** [comment]
Okay merging here! This is definitely an improvement to the action to have the updated container.

**Comment by vsoch** [comment]
Note that I deleted the branch, so if you were testing with it, you can switch to main/master (I forgot which I use here hehe)

**Comment by ax3l** [comment]
No worries, branches must be cleaned! :sparkles:

**Pull request merged**
