### PR TITLE
Always exports results

### PR DESCRIPTION
**Pull request by maelle**

### CODE REVIEW

**Comment by maelle** [comment]
Or did the force pass option ensure a csv is always uploaded? 🤔

**Comment by vsoch** [comment]
good call! But if we run always why do we need the if condition at all (could we not just remove that line?)

**Comment by vsoch** [comment]
Force pass just determines the return code - setting it to true would ensure that the step always passes, but as you might also infer, that isn’t necessarily wanted even if we still want a results file. Did you try just removing the line?

**Comment by vsoch** [comment]
If it’s the case that the next step wouldn’t run at all on failure without always then this is the correct fix. Can you test this out and let me know? Once we’ve confirmed this is correct we can merge here.

**Comment by maelle** [comment]
That was my first issue today, indeed if the URLs check fails then the upload step is skipped, therefore "always" is needed.

**Comment by maelle** [comment]
it could also be if: failure()

**Comment by vsoch** [comment]
okay! Let's change to always then -I think this is the right example to show, because likely the user wants to see the list regardless of the status!

**Pull request merged**
