### PR TITLE
adding save argument to action

### PR DESCRIPTION
**Pull request by vsoch**
This PR will expose the `--save` argument for the action. This will need to be tested with urlchecker-python PR #14 is merged and the quay.io container is built that will allow for the --save argument.

https://github.com/urlstechie/urlchecker-python/pull/14

Signed-off-by: vsoch <vsochat@stanford.edu>

### CODE REVIEW

**Review by SuperKogito — APPROVED** [review]

**Comment by vsoch** [comment]
Actually, since the user can use this action on this branch, let's wait to merge until you are back and have some time to test, and release officially. Nobody will notice the small delay, there is no rush on these things!

**Comment by SuperKogito** [comment]
This looks fine but I have doubt about it. I am not sure if editing the shell file is enough to and & commit the results file in the project. there is one way to find out -I guess- I will just merge and test it.

**Comment by vsoch** [comment]
It's basically adding [the save flag](https://github.com/urlstechie/urlchecker-python#save-results) so you could test that first if you like.

**Comment by vsoch** [comment]
Also you can add more test cases here! https://github.com/urlstechie/urlchecker-action/blob/master/.github/workflows/main.yml#L11 E.g., add one that uses save, and then assert that the file exists.

**Pull request merged**
